### ISSUE TITLE
网页审查工具出现问题

### ISSUE THREAD

**Issue by ice345** [Snoopy1866/blogs#2]
![屏幕截图 2024-07-03 165433](https://github.com/Snoopy1866/blogs/assets/143070544/933e4874-0bc9-4a09-b6ea-6225314abd90)
不知道为什么突然之间不行了，前不久还ok的

**Comment by ice345** [comment]
![屏幕截图 2024-07-03 165725](https://github.com/Snoopy1866/blogs/assets/143070544/1fc49c78-d4de-4553-9566-75db578ab8c6)

**Comment by Snoopy1866** [comment]
这里不是 https://github.com/gkd-kit/inspect 的讨论区，网络错误大概率是 ip 地址变了，请查看手机上 gkd 高级设置的显示的地址。
