### ISSUE TITLE
大佬，关于gkd的教程还会更新吗

### ISSUE THREAD

**Issue by heshi2019** [Snoopy1866/blogs#5]
有些广告跳过，如网易云音乐在打开时弹出的领取有声书的广告，并无具体的文字，而是只有一个叉号

这部分需要使用gkd的关系选择器来选择

大佬的教程好像刚好停在关系选择器之前了

**Comment by Snoopy1866** [comment]
https://github.com/Snoopy1866/blogs/blob/main/software/gkd/gkd-rule-tutorial/gkd-rule-tutorial.md#532-%E5%85%B3%E7%B3%BB%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by heshi2019** [comment]
感谢！
